source 'https://rubygems.org'

ruby '2.0.0' 
gem 'rails', '4.0.5'
gem 'mysql2', '0.3.18'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'bcrypt-ruby'
gem 'execjs'
gem 'therubyracer'
gem 'sidekiq', '~> 2.17.7'
gem 'sidetiq'
gem 'sinatra'
gem 'figaro' 
gem 'browser'
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf', github: 'mileszs/wicked_pdf'
gem 'mime-types', '1.25.1' 
gem 'stripe' 
gem 'bootstrap-datepicker-rails'
gem 'shopify_api', '~> 3.2.1'
gem 'shopify_app', '~> 5.0.2'
gem 'will_paginate', '~> 3.0'
gem 'daemons'
gem 'delayed_job_active_record' 
gem 'axlsx_rails'
gem 'rubyzip', '< 1.0.0'
gem 'attr_encrypted', '~> 1.3.5'
group :development do
  gem 'quiet_assets' # turns off Rails asset pipeline log
  gem 'capistrano',  '~> 3.1'
  gem 'capistrano-rails', '~> 1.1'
  gem 'capistrano-rvm', github: 'capistrano/rvm'
  gem 'capistrano-sidekiq'
  gem 'pry'
  gem 'pry-debugger'
end 
gem 'shipwire', git: 'https://github.com/dfreerksen/shipwire.git', :branch=>'new-api'#,:ref=>'cf358b5855e733dedb0c9c57fc3134d8387f35b7'

group :production do
  gem 'newrelic_rpm'
end
gem 'whenever', :require => false

gem 'ckeditor_rails'
gem 'carmen'  
gem 'carmen-rails'
gem 'country_select'  
gem 'peddler'
gem 'humanize_boolean'
